
apiVersion: k8s.io/v1
kind: Database
metadata:
  name: test-pgsql
  namespace: default
  spec:
    class: db.t2.micro
    engine: postgres
    dbname: test-pgsql
    name: test-pgsql
    password: mysupersecretPW
    username: postgres


  
